### ISSUE TITLE
“Unknown visitor type” in npm package, protagonist

### ISSUE THREAD

**Issue by Ustice** [apiaryio/protagonist#136]
I am trying to convert my API Blueprints to a Postman collection through protagonist (and then through blueman), but when I use protagonist, I am getting the following result, no matter what I do.

```
{
  "element": "parseResult",
  "content": [
    {
      "element": "annotation",
      "meta": {
        "classes": [
          "warning"
        ]
      },
      "attributes": {
        "code": 4,
        "sourceMap": [
          {
            "element": "sourceMap",
            "content": []
          }
        ]
      },
      "content": "Unknown visitor type"
    }
  ]
}
```

I have eliminated the possibility that it is from my code, as I get this result when I simply use the example code of:

```
var result = protagonist.parseSync('# My API');
```

I have tried protagonist 1.2.6 and 1.3.0-pre.0, and I get the same result. It seems to be coming from [here](https://github.com/apiaryio/drafter/blob/master/src/refract/VisitableBy.h#L42), but I don't understand what is causing it.

## System Information

* **OS X** - 10.11.4
* **Node** - 4.4.0

**Comment by kylef** [comment]
@Ustice Would you be able to share with us the blueprint? Or perhaps find a minimal example to reproduce this issue?

This is most likely an issue in Drafter, our underlying parser behind Protagonist.

**Comment by Ustice** [comment]
I tried it with the one given in the example, but I also just tried it with [this one](https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/01.%20Simplest%20API.md). The minimal one in the example gives the same error, but I wanted to make sure that it wasn't that it was missing needed elements.

**Comment by Ustice** [comment]
Also, as a note I used Drafter directly, and I was able to get what looks like the proper result, although converting that to a Postman collection with Blueman is throwing another error, possibly related to a Snow Crash dependency issue in Drafter.

**Comment by honzajavorek** [comment]
Experiencing completely the same behavior: https://github.com/apiaryio/fury-adapter-apib-parser/issues/4

**Comment by honzajavorek** [comment]
The funny thing is that I work on a project where `protagonist` is installed as dev dependency and works as expected in tests. Then I have it installed as Fury.js's dependency and when used through Fury, it returns `Unknown visitor type` for whatever I put in.

So in the same project, during the same `npm test` run, the same version of protagonist, just installed in different folders, behaves differently. One works correctly, the other one has this issue.

**Comment by pksunkara** [comment]
This should be fixed in the next pre release of protagonist.

**Comment by honzajavorek** [comment]
@pksunkara I installed `v1.3.0-pre.1` and I'm still experiencing the same error.

**Comment by honzajavorek** [comment]
So far it seems:

- it affects all three latest versions of protagonist
- can occur on a single installation of it (I have two independent protagonists of identical versions installed inside the same project, inside one `node_modules` folder, just as dependencies of different parent projects, and one seems to work and the other one does not)
- when it occurs, if protagonist is fed by any blueprint, protagonist just returns the warning and nothing else

Can it be a problem with build of the protagonist itself? Just guessing.

**Comment by honzajavorek** [comment]
Just for the record, I created a little sample app where the problem can be reproduced: https://github.com/apiaryio/protagonist-visitor-type-issue Build: https://travis-ci.org/apiaryio/protagonist-visitor-type-issue

**Comment by pksunkara** [comment]
`v1.3.0-pre.1` is parsing it correctly.

**Comment by pksunkara** [comment]
This is fixed now.
