### ISSUE TITLE
Possible Windows Regression

### ISSUE THREAD

**Issue by danielgtaylor** [apiaryio/protagonist#35]
It looks like multiple users have reported a potential regression on Windows via danielgtaylor/aglio#78. It seems directly related to the version bump between Protagonist 0.16 and 0.17 when dealing with fairly large files.

**Comment by zdne** [comment]
Thanks for reporting @danielgtaylor! 

Do you know whether this is a performance issue (= the parsing is really slow) or is it a complete failure (file won't parse)?

**Comment by pksunkara** [comment]
[This](https://gist.github.com/NobodysNightmare/5095a25d6f1c9662db46) is the failing blueprint on windows in the above mentioned issue.

**Comment by NobodysNightmare** [comment]
@zdne It is a complete failure.

Please note that the blueprint referenced by @pksunkara is a **shortened** version of [the original blueprint](https://github.com/opf/openproject/blob/a3839a19c2e66b2ae879b2f3374003f805660a0a/doc/apiv3-documentation.apib).

The *shortened* version fails **unreliably** (fails approx. 3 of 4 runs, meaning it *succeeds* 1 of 4 runs!). The full version of the blueprint fails reliably for me and some other windows machines I have tested (see [original report](https://github.com/danielgtaylor/aglio/issues/78)).

**Comment by zdne** [comment]
Hey, just want to assure that I will look into this issue & fix it ASAP. Thanks.

**Comment by 3mind-** [comment]
@zdne any progress already that you can share?
Thanks

**Comment by zdne** [comment]
@3mind- No updates yet, sorry. Will get to it during this week.

**Comment by ahmad2x4** [comment]
I'm experiencing the same issue randomly on Windows

**Comment by zdne** [comment]
Gentlemen, 
 I have looked into the issue and current status is that I am not able to reproduce this issue. 

I have fixed the tests suite, added Protagonist in Windows CI testing (see https://ci.appveyor.com/project/zdne/protagonist/branch/master) and released new version [v0.17.2](https://github.com/apiaryio/protagonist/releases/tag/v0.17.2)

Tested on Windows 7 and Windows Sever 2012. 

Can you please try to install the latest Protagonist  (0.17.2) and run `npm test`? If this passes I would like to ask you for an example blueprint, node version, windows version, compiler (msvc) version so I can try to reproduce this problem.

Thanks for the help!

**Comment by 3mind-** [comment]
Sorry for the late reply.

I found time now to update Protagonist to version 0.17.2 as suggested, and the documentation generation is **working** now again. :+1: 

I tried it locally as well as on the build-server (Jenkins) multiple times, until now without failures.

Thanks a lot!

**Comment by 3mind-** [comment]
unfortunately I have to take my previous statement back.

it still fails roughly 50% of the time for me (without any changes to the markdown...)

**Comment by zdne** [comment]
> it still fails roughly 50% of the time for me (without any changes to the markdown...)

What fails. Can you describe it in more detail. Also please provide versions of windows, compiler, node, and node-gyp. Thanks.

**Comment by ksmyth** [comment]
I can repro with node x64 v0.10.37, node-gyp 1.03, protagonist 60f2fbe9b, VS2010SP1, Win 8.1. protagonist.parse fails with an access violation, but only sometimes. (It seems to fail more often when you run outside of the debugger)

Please see:
https://gist.github.com/ksmyth/e631520577c6238166e1

Let me know if you need further info.

**Comment by zdne** [comment]
@ksmyth hm this is worry some – any chance of getting a blueprint (snippet) that is causing this?

**Comment by zdne** [comment]
The line 

`00000000`2268d190 00007ffc`a0b49c0c protagonist!snowcrash::Reference::Reference+0xe2`

Should give us some clue tho – looks like the blueprint includes some model referencing?

**Comment by ksmyth** [comment]
https://gist.githubusercontent.com/ksmyth/c35d0dc4d4b43fc1b6eb/raw/89d031480d20b242c248f5fa90de689c3e1870b9/gistfile1.txt is the input file.

**Comment by kylef** [comment]
It looks like this has been fixed for a while now via https://github.com/apiaryio/snowcrash/issues/329.

Please re-open if this is not the case.
